// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

//! # Mapping the Serde datamodel to the Avro datamodel
//! 
//! When manually mapping Rust types to a Avro schema, or the reverse, it is important to understand
//! how the datamodels are mapped. This should only be done in very specific circumstances, most users
//! should use the [`AvroSchema`] derive macro.
//! 
//! Only the schemas as generated by the [`AvroSchema`] derive macro and the mapping as defined here are
//! supported. Any other behaviour is not supported.
//! 
//! ## Primitive types
//! - `bool` -> [`Schema::Boolean`]
//! - `i8`, `i16`, `i32`, `u8`, `u16` -> [`Schema::Int`]
//! - `i64`, `u32` -> [`Schema::Long`]
//! - `u64` -> [`Schema::Fixed`]`(name: "u64", size: 8)`
//!     - This is not a `Schema::Long` as that is a signed number of maximum 64 bits.
//! - `i128` -> [`Schema::Fixed`]`(name: "i128", size: 16)`
//! - `u128` -> [`Schema::Fixed`]`(name: "u128", size: 16)`
//! - `f32` -> [`Schema::Float`]
//! - `f64` -> [`Schema::Double`]
//! - `char` -> [`Schema::String`]
//!     - Only one character allowed, deserializer will return an error for strings with more than one character.
//! - `tuple` -> [`Schema::Record`] with a field for every tuple index
//! - `[T; N]` -> [`Schema::Record`] with a field for every array index
//!     - To (de)serialize as a [`Schema::Array`] use [`apache_avro::serde::array`]
//!     - To (de)serialize as a [`Schema::Fixed`] use [`apache_avro::serde::fixed`]
//!     - To (de)serialize as a [`Schema::Bytes`] use [`apache_avro::serde::bytes`]
//! 
//! ## Standard library types
//! - `string` -> [`Schema::String`]
//! - ``
//! 
//! 
//! [`apache_avro::serde::array`]: crate::serde::array
//! [`apache_avro::serde::bytes`]: crate::serde::bytes
//! [`apache_avro::serde::fixed`]: crate::serde::fixed
//! [`AvroSchema`]: crate::AvroSchema
//! [`Schema::Array`]: crate::schema::Schema::Array
//! [`Schema::Boolean`]: crate::schema::Schema::Boolean
//! [`Schema::Bytes`]: crate::schema::Schema::Bytes
//! [`Schema::Double`]: crate::schema::Schema::Double
//! [`Schema::Fixed`]: crate::schema::Schema::Fixed
//! [`Schema::Float`]: crate::schema::Schema::Float
//! [`Schema::Int`]: crate::schema::Schema::Int
//! [`Schema::Long`]: crate::schema::Schema::Long
//! [`Schema::Record`]: crate::schema::Schema::Record
//! [`Schema::String`]: crate::schema::Schema::String